---
- name: Enable Php7.0 curl extension
  become: yes
  become_method: sudo
  command: phpenmod curl
  args:
    creates: /etc/php/7.0/fpm/conf.d/20-curl.ini
  notify:
    - restart php7.0-fpm

- name: Enable Php7.0 gd extension
  become: yes
  become_method: sudo
  command: phpenmod gd
  args:
    creates: /etc/php/7.0/fpm/conf.d/20-gd.ini
  notify:
    - restart php7.0-fpm

- name: Enable Php7.0 imagick extension
  become: yes
  become_method: sudo
  command: phpenmod imagick
  args:
    creates: /etc/php/7.0/fpm/conf.d/20-imagick.ini
  notify:
    - restart php7.0-fpm

- name: Enable Php7.0 intl extension
  become: yes
  become_method: sudo
  command: phpenmod intl
  args:
    creates: /etc/php/7.0/fpm/conf.d/20-intl.ini
  notify:
    - restart php7.0-fpm

- name: Enable Php7.0 json extension
  become: yes
  become_method: sudo
  command: phpenmod  json
  args:
    creates: /etc/php/7.0/fpm/conf.d/20-json.ini
  notify:
    - restart php7.0-fpm

- name: Enable Php7.0 mcrypt extension
  become: yes
  become_method: sudo
  command: phpenmod mcrypt
  args:
    creates: /etc/php/7.0/fpm/conf.d/20-mcrypt.ini
  notify:
    - restart php7.0-fpm

- name: Enable Php7.0 mysqli extension
  become: yes
  become_method: sudo
  command: phpenmod mysqli
  args:
    creates: /etc/php/7.0/fpm/conf.d/20-mysqli.ini
  notify:
    - restart php7.0-fpm

- name: Enable Php7.0 mysql extension
  become: yes
  become_method: sudo
  command: phpenmod mysql
  args:
    creates: /etc/php/7.0/fpm/conf.d/20-mysql.ini
  notify:
    - restart php7.0-fpm

- name: Enable Php7.0 pdo extension
  become: yes
  become_method: sudo
  command: phpenmod pdo
  args:
    creates: /etc/php/7.0/fpm/conf.d/10-pdo.ini
  notify:
    - restart php7.0-fpm

- name: Enable Php7.0 opcache extension
  become: yes
  become_method: sudo
  command: phpenmod opcache
  args:
    creates: /etc/php/7.0/fpm/conf.d/05-opcache.ini
  notify:
    - restart php7.0-fpm

- name: Enable Php7.0 pdo_mysql extension
  become: yes
  become_method: sudo
  command: phpenmod pdo_mysql
  args:
    creates: /etc/php/7.0/fpm/conf.d/20-pdo_mysql.ini
  notify:
    - restart php7.0-fpm

- name: Enable Php7.0 pdo_sqlite extension
  become: yes
  become_method: sudo
  command: phpenmod pdo_sqlite
  args:
    creates: /etc/php/7.0/fpm/conf.d/20-pdo_sqlite.ini
  notify:
    - restart php7.0-fpm

- name: Enable Php7.0 sqlite3 extension
  become: yes
  become_method: sudo
  command: phpenmod sqlite3
  args:
    creates: /etc/php/7.0/fpm/conf.d/20-sqlite3.ini
  notify:
    - restart php7.0-fpm

- name: Enable Php7.0 xdebug extension
  become: yes
  become_method: sudo
  command: phpenmod xdebug
  args:
    creates: /etc/php/7.0/fpm/conf.d/20-xdebug.ini
  notify:
    - restart php7.0-fpm

- name: Enable Php7.0 mbstring extension
  become: yes
  become_method: sudo
  command: phpenmod mbstring
  args:
    creates: /etc/php/7.0/fpm/conf.d/20-mbstring.ini
  notify:
    - restart php7.0-fpm

- name: Enable Php7.0 zip extension
  become: yes
  become_method: sudo
  command: phpenmod zip
  args:
    creates: /etc/php/7.0/fpm/conf.d/20-zip.ini
  notify:
    - restart php7.0-fpm

- name: Enable Php7.0 bz2 extension
  become: yes
  become_method: sudo
  command: phpenmod bz2
  args:
    creates: /etc/php/7.0/fpm/conf.d/20-bz2.ini
  notify:
    - restart php7.0-fpm

- name: Enable Php7.0 xml extension
  become: yes
  become_method: sudo
  command: phpenmod xml
  args:
    creates: /etc/php/7.0/fpm/conf.d/20-xml.ini
  notify:
    - restart php7.0-fpm
