---
- name: Install Php7.0
  become: yes
  become_method: sudo
  apt: name={{ item }} update_cache=yes state=latest cache_valid_time=3600
  with_items:
    - php7.0
    - php7.0-json
    - php7.0-sqlite3
    - php-xdebug
    - php7.0-cli
    - php7.0-fpm
    - php-imagick
    - php7.0-common
    - php7.0-gd
    - php7.0-curl
    - php7.0-mcrypt
    - php7.0-mysql
    - php7.0-intl
    - php-pear
    - php7.0-dev
    - php7.0-mbstring
    - php7.0-zip
    - php7.0-bz2
    - php7.0-xml